---
## For some reason this segfaults on my cubietruck...
#- name: Update the apt cache unless it was just updated
#  apt: update_cache=yes cache_valid_time=10

- name: Upgrade packages
  apt: upgrade=yes
  when: apt_basic__upgrade_packages
