---
- hosts: all
  vars_files:
    - config.yml
  tasks:
    - shell: "echo Provisioned on $(date) > {{ data_dir }}/provisioning.txt"
  roles:
    - { role: common }
    - { role: external_data_drive, when: external_data_drive__enabled }
    - { role: users, when: users__enabled }
    - { role: apt_basic, when: apt_basic__enabled }
    - { role: apt_localrepo, when: apt_localrepo__enabled }
    - { role: desktop, when: desktop__enabled }
    - { role: kalite, when: kalite__enabled }
    - { role: wikipedia, when: wikipedia__enabled }
    # Always run this one last, since it will build the ISO
    - { role: build_iso, when: build_iso__enabled }
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

- hosts: cubietruck
  vars_files:
    - config.yml
  roles:
    - { role: cubietruck }
